columnSuffix: null
handle: socialSites
instructions: null
name: 'Social Sites'
searchable: false
settings:
  createButtonLabel: 'New site'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - d89eaa6c-1910-44f4-a943-5c8e27658de7 # Social Site
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
