columnSuffix: null
handle: socialSiteName
instructions: null
name: 'Social Site Name'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - Facebook
        -
          - value
          - facebook
        -
          - icon
          - facebook
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Instagram
        -
          - value
          - instagram
        -
          - icon
          - instagram
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - LinkedIn
        -
          - value
          - linkedin
        -
          - icon
          - linkedin
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Pinterest
        -
          - value
          - pinterest
        -
          - icon
          - pinterest
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - X
        -
          - value
          - x
        -
          - icon
          - square-x-twitter
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - YouTube
        -
          - value
          - youtube
        -
          - icon
          - youtube
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Bluesky
        -
          - value
          - bluesky
        -
          - icon
          - square-bluesky
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
