columnSuffix: null
handle: socialSiteUrl
instructions: null
name: 'Social Site URL'
searchable: false
settings:
  fullGraphqlData: true
  maxLength: 255
  showLabelField: false
  typeSettings:
    __assoc__:
      -
        - url
        -
          __assoc__:
            -
              - allowRootRelativeUrls
              - ''
            -
              - allowAnchors
              - ''
            -
              - allowCustomSchemes
              - ''
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
