dateModified: 1772228049
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - dateUpdated
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      page: Content
      tableAttributes:
        - section
        - dateUpdated
        - uri
      type: native
    -
      heading: Pages
      key: 'heading:6647ee96-16f2-42da-81f8-5a5614bd5445'
      page: Content
      type: heading
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'single:90775891-8a83-4dd6-b2c0-0462aceb52d4' # Homepage
      page: Content
      tableAttributes:
        - status
        - dateUpdated
        - link
      type: native
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:b7a660f1-cbad-4067-8031-b237c204ab41' # Pages
      page: Content
      tableAttributes:
        - dateUpdated
        - uri
      type: native
    -
      heading: Global
      key: 'heading:0ea7cbf3-7a05-4464-afac-6e698600f758'
      page: Global
      type: heading
    -
      defaultSort:
        - id
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'single:c9b07bce-eaac-4cc4-82ab-d7536fd463a0' # Global Social
      page: Global
      tableAttributes:
        - dateUpdated
      type: native
    -
      heading: 'Error Pages'
      key: 'heading:2f1b7a47-cf5c-408e-92d7-e20515543041'
      page: Global
      type: heading
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:a8919477-f7b3-4f9b-be48-596ba606e393' # Error Pages
      page: Global
      tableAttributes:
        - slug
      type: native
elementSourcesPages:
  craft\elements\Entry:
    Global:
      icon: globe
email:
  fromEmail: chris@malven.co
  fromName: your-project-title
  transportType: craft\mail\transportadapters\Sendmail
fs:
  local:
    hasUrls: true
    name: Local
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: '@assetPath'
meta:
  __names__:
    0eec63d1-8a33-4f6a-83a5-00c027db46dc: your-project-title # your-project-title
    0f62a524-edb1-4f42-8319-5fa437d5a756: 'Text (Rich - Simple)' # Text (Rich - Simple)
    1eb79bf6-fb1c-4811-83fc-135aca7bfc89: Heading # Heading
    6d6999fd-cf25-4011-91bb-6ea9b844274b: 'Post Content' # Post Content
    7b4eb678-108a-4921-9361-93e866c44efa: 'User Editors' # User Editors
    8e9916cc-4334-4a7e-9ba6-e6aae9238c81: 'Text (Plain - Single Line)' # Text (Plain - Single Line)
    9d6e156d-8dd4-4224-a69a-f46d32d53774: Standard # Standard
    31abb75d-dc87-4ff3-a413-bb161bd3a59f: your-project-title # your-project-title
    109bc20e-6e6a-4466-885c-030237bbbc46: 'Text (Plain - Multiline)' # Text (Plain - Multiline)
    223e7dac-c6de-46ba-9144-0ee4c62734c4: 'Page Content' # Page Content
    380a83b9-344d-415b-a3f4-8b389ef61717: SEO # SEO
    507bbcf8-f9bf-4845-9b14-829d155d2a96: Simple # Simple
    762c90cb-e904-42b1-a0ea-a82b1ddbe561: Images # Images
    9912afa3-ca03-49ab-a46b-7aabfa7f263d: 'Error Page' # Error Page
    253489f3-4e59-48ac-a725-d8592cb0ed1e: Page # Page
    364133aa-0996-4ac2-8361-def609a990a0: 'Global Social' # Global Social
    90775891-8a83-4dd6-b2c0-0462aceb52d4: Homepage # Homepage
    a41668f7-a432-4cc4-a09b-609538ea0125: Homepage # Homepage
    a8919477-f7b3-4f9b-be48-596ba606e393: 'Error Pages' # Error Pages
    ac35dbca-18f6-4f3d-a9ac-94c95bd7bf1c: 'Link Item' # Link Item
    ad966c15-02a7-47c1-b099-8822cd581301: 'Image / Video (Multiple)' # Image / Video (Multiple)
    adacfc6e-cbe6-4bc6-b486-3c04cfbd4b0b: Text # Text
    b7a660f1-cbad-4067-8031-b237c204ab41: Pages # Pages
    bcb6b0c7-7c1f-4d59-8d27-520b3d9ecca9: 'Social Site Name' # Social Site Name
    bdf04aed-258a-4c46-b577-0436c1c68003: 'Social Site URL' # Social Site URL
    c9b07bce-eaac-4cc4-82ab-d7536fd463a0: 'Global Social' # Global Social
    cdb419d9-a1e7-471e-ae31-20361997cf3b: 'Social Sites' # Social Sites
    cdebb3ec-ae8f-4b56-ab25-7afbf135a0d3: 'Post Content' # Post Content
    d89eaa6c-1910-44f4-a943-5c8e27658de7: 'Social Site' # Social Site
    db405b1d-69f1-4eca-8a10-2f1545594476: 'Public Schema' # Public Schema
    dbbb6437-d106-40f2-a3ca-d539087f53a6: 'Image / Video' # Image / Video
    f213dd53-a8ec-4985-b00c-f544ba83c531: Editors # Editors
plugins:
  aws-s3:
    edition: standard
    enabled: true
    schemaVersion: '2.0'
  blitz:
    edition: standard
    enabled: true
    licenseKey: HGVNS2HNHYNTF992JUBYGSEL
    schemaVersion: 5.12.0
    settings:
      maxUriLength: 2048
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  craft-ray:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      expandSingles: true
      redirectToEntry: true
  hyper:
    edition: standard
    enabled: true
    licenseKey: 0S7BAJ9N082V9A5ZY8B2PCKU
    schemaVersion: 1.0.0
  imager-x:
    edition: lite
    enabled: true
    licenseKey: P2W66U20QF34WYF2Y3OWGYGM
    schemaVersion: 4.0.0
  navigation:
    edition: standard
    enabled: true
    licenseKey: 4TH2AWI8M809O4SJIJAE3G0O
    schemaVersion: 2.1.2
  queue-monitor:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      failedJobUserGroup: null
      restartFailedJobs: true
      restartInterval: 10
      restartMaxTries: 3
      sendFailedJobEmail: false
  retour:
    edition: standard
    enabled: true
    licenseKey: FY52PHR9RN31K932TUWF6TS2
    schemaVersion: 3.0.12
    settings:
      alwaysStripQueryString: false
      automaticallyTrimStatistics: true
      createUriChangeRedirects: true
      csvColumnDelimiter: ','
      dynamicRedirectDisplayLimit: 100
      enableApiEndpoint: false
      enableStatistics: true
      pluginName: Redirects
      preserveQueryString: false
      recordRemoteIp: true
      refreshIntervalSecs: 5
      resolveCraftSites: true
      setNoCacheHeaders: true
      staticRedirectDisplayLimit: 100
      statisticsRateLimitMs: 3600000
      statsDisplayLimit: 1000
      statsStoredLimit: 1000
      stripQueryStringFromStats: true
      uriChangeRedirectSrcMatch: pathonly
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 3N7V5B8W827NHW54ZF1MOWVI
    schemaVersion: 3.0.13
  sherlock:
    edition: lite
    enabled: true
    schemaVersion: 5.1.0
    settings:
      apiKey: zblzvmppfcewwwpsyxipdxrwqwtkhcuf
      blowfishHashCost:
        __assoc__:
          -
            - threshold
            - 13
      contentSecurityPolicy:
        __assoc__:
          -
            - canFail
            - true
      contentSecurityPolicySettings:
        __assoc__:
          -
            - enabled
            - false
          -
            - enforce
            - false
          -
            - header
            - true
          -
            - directives
            -
              -
                - 1
                - default-src
                - "'self'"
      cooldownDuration:
        __assoc__:
          -
            - threshold
            - 300
      cors:
        __assoc__:
          -
            - forceFail
            - true
      craftFilePermissions:
        __assoc__:
          -
            - canFail
            - true
      craftFolderPermissions:
        __assoc__:
          -
            - canFail
            - true
      craftFoldersAboveWebRoot:
        __assoc__:
          -
            - canFail
            - true
      criticalCraftUpdates:
        __assoc__:
          -
            - forceFail
            - true
      criticalPluginUpdates:
        __assoc__:
          -
            - forceFail
            - true
      defaultDirMode:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 509
      defaultFileMode:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 436
      defaultTokenDuration:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 86400
      devMode:
        __assoc__:
          -
            - forceFail
            - true
      disabledTests: null
      elevatedSessionDuration:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 300
      enableCsrfProtection:
        __assoc__:
          -
            - canFail
            - true
      expectCT:
        __assoc__:
          -
            - canFail
            - true
      headerProtectionSettings:
        __assoc__:
          -
            - enabled
            - true
          -
            - headers
            -
              -
                - true
                - Referrer-Policy
                - no-referrer-when-downgrade
              -
                - true
                - Strict-Transport-Security
                - max-age=15552000
              -
                - true
                - X-Content-Type-Options
                - nosniff
              -
                - true
                - X-Frame-Options
                - SAMEORIGIN
              -
                - true
                - X-Xss-Protection
                - '1; mode=block'
      highSecurityLevel: false
      httpsControlPanel:
        __assoc__:
          -
            - forceFail
            - true
      httpsFrontEnd:
        __assoc__:
          -
            - forceFail
            - true
      integrationSettings: null
      invalidLoginWindowDuration:
        __assoc__:
          -
            - threshold
            - 3600
      maxInvalidLogins:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 5
      maxScans: false
      monitor: false
      notificationEmailAddresses: chris@malven.co
      phpComposerVersion:
        __assoc__:
          -
            - canFail
            - true
      phpVersion:
        __assoc__:
          -
            - canFail
            - true
          -
            - thresholds
            -
              __assoc__:
                -
                  - '8.0'
                  - '2023-11-26'
                -
                  - '8.1'
                  - '2024-11-25'
                -
                  - '8.2'
                  - '2025-12-08'
      preventUserEnumeration:
        __assoc__:
          -
            - canFail
            - true
      referrerPolicy:
        __assoc__:
          -
            - canFail
            - true
      rememberedUserSessionDuration:
        __assoc__:
          -
            - threshold
            - 12096004
      requireEmailVerification:
        __assoc__:
          -
            - canFail
            - true
      sanitizeSvgUploads:
        __assoc__:
          -
            - canFail
            - true
      sendPoweredByHeader:
        __assoc__:
          -
            - canFail
            - false
      strictTransportSecurity:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 15552000
      testToEmailAddress:
        __assoc__:
          -
            - canFail
            - true
      translationDebugOutput:
        __assoc__:
          -
            - canFail
            - true
      useSecureCookies:
        __assoc__:
          -
            - canFail
            - true
      userSessionDuration:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 3600
      verificationCodeDuration:
        __assoc__:
          -
            - canFail
            - true
          -
            - threshold
            - 86400
      webAliasInSiteBaseUrl:
        __assoc__:
          -
            - forceFail
            - true
      webAliasInVolumeBaseUrl:
        __assoc__:
          -
            - forceFail
            - true
      xContentTypeOptions:
        __assoc__:
          -
            - canFail
            - true
      xFrameOptions:
        __assoc__:
          -
            - canFail
            - true
system:
  edition: pro
  live: true
  name: your-project-title
  schemaVersion: 5.9.0.8
  timeZone: America/Los_Angeles
