defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9912afa3-ca03-49ab-a46b-7aabfa7f263d # Error Page
handle: errorPages
maxAuthors: 1
name: 'Error Pages'
propagationMethod: all
siteSettings:
  0eec63d1-8a33-4f6a-83a5-00c027db46dc: # your-project-title
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
